version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: todos
      POSTGRES_PASSWORD: todos123456
      POSTGRES_DB: todos
  backend:
    build:
      context: .
    expose:
      - 8000
    command: bash -c "
      ./wait-for-postgres.sh db
      && python manage.py migrate
      && gunicorn to_do.wsgi -b 0.0.0.0:8000
      "
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend
  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - nginx